{-
Read .st graphs (initial fragment) from files at help/graph and write both som/Sc3-Help/Sc3HelpGraph.ext.som and st/Sc3-Help.st
To avoid pretty printing this just copies the help text, prepending a return mark to the last line.
This means the last line of each help graph _must_ be a simple expression.
Both formats are written because the .som -> .st translator rewrites the graph and deletes the comment...
-}

import Data.Char {- base -}
import Data.List {- base -}

import Data.List.Split {- split -}

import System.FilePath {- filepath -}

import Music.Theory.Directory {- hmt-base -}

som_methods_preamble = "\"Autogenerated\"\nSc3HelpGraph = Sc3HelpGraph ("

som_methods_postamble = ")"

st_methods_prefix = "!Sc3HelpGraph methodsFor: 'Sc Help Graphs'!"

-- > file_name_to_method_name "f0-tw-1395878538297892865.st" == "f0Tw1395878538297892865"
file_name_to_method_name fn =
  let p1:p = splitOn "-" (dropExtension fn)
      capitalise x = toUpper (head x) : tail x
  in concat (p1 : map capitalise p)

-- > putStrLn $ runner_text "f0Tw1395878538297892865"
runner_text nm =
  ["\""
  ,"Sc3HelpGraph new " ++ nm ++ " play."
  ,"Sc3 reset."
  ,"\""]

indent_text_by prefix = map (prefix ++) . lines

stsc3_dir = "/home/rohan/sw/stsc3/"
graph_dir = stsc3_dir ++ "help/graph/"

proc_file_text forSt fn ln =
  let cm = ln !! 0
      bdy = drop 1 (init ln)
      ret = last ln
      nm = file_name_to_method_name fn
      pr = cm : concat [runner_text nm, bdy, [ '^' : ret]]
  in if forSt
     then unlines (nm : map ("\t" ++) pr)
     else unlines (("\n" ++ nm ++ " = (") : map ("\t" ++) pr)

-- > proc_file "f0-tw-1395878538297892865.st" >>= putStrLn
proc_file forSt fn = do
  txt <- readFile (graph_dir ++ fn)
  let frg = takeWhile (/= "") (lines txt)
  return (proc_file_text forSt fn frg)

main = do
  fn_list <- dir_subset_rel [".st"] graph_dir
  st_mth <- mapM (proc_file True) fn_list
  som_mth <- mapM (proc_file False) fn_list
  let endWith e = unlines . map (++ e)
  writeFile (stsc3_dir ++ "som/Sc3-Help/Sc3HelpGraph.ext.som") (unlines [som_methods_preamble, endWith ")" som_mth, som_methods_postamble])
  writeFile (stsc3_dir ++ "st/Sc3-Help.st") (unlines [st_methods_prefix, endWith "!" st_mth, "!"])
