// When Select is audio rate, _all_ arguments (including all array values) must be audio rate...
+ Select { *new { arg which, array;	^this.multiNewList(['control', which] ++ array) } }

// Should be Filter...
+ Splay { *new { arg inArray, spread = 1, level = 1, center = 0.0, levelComp = true; ^Splay.ar(inArray, spread, level, center, levelComp) } }
