!EnvSpec methodsFor: 'accessing'!
curves ^curves !
curves: x curves := x. !
levels ^levels !
levels: x levels := x. !
loopNode ^loopNode !
loopNode: x loopNode := x. !
offset ^offset !
offset: x offset := x. !
releaseNode ^releaseNode !
releaseNode: x releaseNode := x. !
times ^times !
times: x times := x. !
!

!EnvPerc methodsFor: 'accessing'!
  attackTime ^attackTime !
  attackTime: x attackTime := x. !
  curve ^curve !
  curve: x curve := x. !
  level ^level !
  level: x level := x. !
  releaseTime ^releaseTime !
  releaseTime: x releaseTime := x. !
!

!EnvLinen methodsFor: 'accessing'!
  attackTime ^attackTime !
  attackTime: x attackTime := x. !
  curve ^curve !
  curve: x curve := x. !
  level ^level !
  level: x level := x. !
  releaseTime ^releaseTime !
  releaseTime: x releaseTime := x. !
  sustainTime ^sustainTime !
  sustainTime: x sustainTime := x. !
!

!EnvASR methodsFor: 'accessing'!
  attackTime ^attackTime !
  attackTime: x attackTime := x. !
  curve ^curve !
  curve: x curve := x. !
  releaseTime ^releaseTime !
  releaseTime: x releaseTime := x. !
  sustainLevel ^sustainLevel !
  sustainLevel: x sustainLevel := x. !
!

!EnvADSR methodsFor: 'accessing'!
  attackTime ^attackTime !
  attackTime: x attackTime := x. !
  curve ^curve !
  curve: x curve := x. !
  decayTime ^decayTime !
  decayTime: x decayTime := x. !
  peakLevel ^peakLevel !
  peakLevel: x peakLevel := x. !
  releaseTime ^releaseTime !
  releaseTime: x releaseTime := x. !
  sustainLevel ^sustainLevel !
  sustainLevel: x sustainLevel := x. !
!

!EnvSine methodsFor: 'accessing'!
  dur ^dur !
  dur: x dur := x. !
  level ^level !
  level: x level := x. !
!
