fetch-osc:
	wget https://unpkg.com/osc@2.4.2/dist/osc-browser.js

fetch-scynth-wasm:
	wget https://scsynth.iem.sh/scsynth.js
	wget https://scsynth.iem.sh/scsynth.wasm
	wget https://scsynth.iem.sh/scsynth.worker.js
