name: ci

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }}, ghc-${{ matrix.versions.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        versions:
          - ghc: latest
            cabal: latest
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.versions.ghc }}
          cabal-version: ${{ matrix.versions.cabal }}
      - name: Build
        run: |
          cabal update
          cabal install --installdir public --install-method copy
          zip -r public/stsc3-${{ runner.os }}.zip public/stsc3 public/stc-to-js
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_id }}
          files: public/stsc3-${{ runner.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
